name: room_track_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
  package_info_plus: ^3.0.6
  flutter_riverpod: ^2.5.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/outlook.svg
    - assets/profile_placeholder.png
    - assets/search.svg
    - assets/room.svg
    - assets/config.svg
    - assets/building.svg
    - assets/arrow_forward.svg
    - assets/home.svg
    - assets/map.svg
    - assets/pc.svg

