name: room_track_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  share_plus: ^10.0.3
  url_launcher: ^6.1.7
  package_info_plus: ^8.0.3
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.8
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/outlook.svg
    - assets/profile_placeholder.png
    - assets/search.svg
    - assets/room.svg
    - assets/config.svg
    - assets/building.svg
    - assets/arrow_forward.svg
    - assets/home.svg
    - assets/map.svg
    - assets/pc.svg

