// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YH_wTCaMxgeGhoAFlBS7IzPwQnD0idE',
    appId: '1:852491266001:web:c316db41a96de5e453a2f0',
    messagingSenderId: '852491266001',
    projectId: 'room-track-bfc12',
    authDomain: 'room-track-bfc12.firebaseapp.com',
    storageBucket: 'room-track-bfc12.appspot.com',
    measurementId: 'G-K3M3ZB9612',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5lHqqGCECdJk74crjebo_sDQnZmIuHQ',
    appId: '1:852491266001:android:2c3ae61e2d50bdc253a2f0',
    messagingSenderId: '852491266001',
    projectId: 'room-track-bfc12',
    storageBucket: 'room-track-bfc12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu13kzAnUGTDbZSbESoe91n8dZzIc9NZI',
    appId: '1:852491266001:ios:651b242c60812a2a53a2f0',
    messagingSenderId: '852491266001',
    projectId: 'room-track-bfc12',
    storageBucket: 'room-track-bfc12.appspot.com',
    iosBundleId: 'com.example.roomTrackFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu13kzAnUGTDbZSbESoe91n8dZzIc9NZI',
    appId: '1:852491266001:ios:651b242c60812a2a53a2f0',
    messagingSenderId: '852491266001',
    projectId: 'room-track-bfc12',
    storageBucket: 'room-track-bfc12.appspot.com',
    iosBundleId: 'com.example.roomTrackFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_YH_wTCaMxgeGhoAFlBS7IzPwQnD0idE',
    appId: '1:852491266001:web:ebf7132fc977535b53a2f0',
    messagingSenderId: '852491266001',
    projectId: 'room-track-bfc12',
    authDomain: 'room-track-bfc12.firebaseapp.com',
    storageBucket: 'room-track-bfc12.appspot.com',
    measurementId: 'G-BGJJP52S79',
  );

}